FROM node:12.18.1

ENV NODE_ENV=ci

# I think this is the work directory in the container?
WORKDIR /app

COPY ["package.json", "package-lock.json*", "./"]

RUN npm install ts-node

RUN npm install --production=false

COPY . .

CMD ["npm", "run", "test"]

